# Generated by Django 6.0.6 on 2026-06-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('qualification', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('guardian_name', models.CharField(max_length=50)),
                ('guardian_occupation', models.CharField(max_length=20)),
                ('guardian_mobile', models.CharField(max_length=10)),
                ('courses', models.CharField(choices=[('PHP Full Stack', 'PHP Full Stack'), ('Python Full Stack', 'Python Full Stack'), ('Java Full Stack', 'Java Full Stack'), ('C#.NET Core 7 Full Stack', 'C#.NET Core 7 Full Stack'), ('MEAN Full Stack', 'MEAN Full Stack'), ('MERN Full Stack', 'MERN Full Stack'), ('Data Science & AI', 'Data Science & AI'), ('Data Science - Gen AI', 'Data Science - Gen AI'), ('Python Mastery', 'Python Mastery'), ('Flutter Mobile App Development', 'Flutter Mobile App Development'), ('UI/UX Designing', 'UI/UX Designing'), ('Digital Marketing Master Program', 'Digital Marketing Master Program')], max_length=100)),
                ('training_mode', models.CharField(choices=[('Live online', 'Live online'), ('Classroom', 'Classroom')], max_length=50)),
                ('location', models.CharField(choices=[('Technopark TVM', 'Technopark TVM'), ('hampanoor TVM', 'Thampanoor TVM'), ('Kochi', 'Kochi'), ('Nagercoil', 'Nagercoil'), ('Online', 'Online')], max_length=50)),
                ('timing', models.CharField(choices=[('Between 8am - 10am', 'Between 8am - 10am'), ('Between 9am - 1pm', 'Between 9am - 1pm'), ('Between 1am - 6pm', 'Between 1pm - 6pm'), ('Between 6pm - 10pm', 'Between 6pm - 10pm')], max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'StudentDetails',
            },
        ),
    ]
